[[jlqml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3056127b04f663f3fc399c63ded40fb0f5a21e45"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "47d47b68a3496bb69a1c6b5e7619353a25385bf4499ce2849d44b66f92c48f3e"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc06f4523d240386fa25724ea6993c4841d81f7d"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "fcf67f5ed7af43111516f119a416994f4d82dc5704a02358469dab5a32abf130"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4165622ec359387b4746a14bfbe9ceb8cab46f8"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "d1d710fffc17d3f459226efe17207409a153860c45656b5ec98aa933ac8155b3"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[jlqml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "098c6c093567863a76653e1a7704926fe93bf0ec"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "21e4be6601197ce9dd2e7facd5b354a6bd1eeea0fbe03a6d094310fcc841650c"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "238635cb52e205d3fdf728f704bec229bdeb1c8a"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "000901b8dcee2c3fc024b9d03dc6c2ceff0baff2c6808fe58ba9d8d119554f0a"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bdc313fba6a81e1377a0b1cd9543d73557bb13d"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "14cfd104ffcbb104b462250d7c997c04dc5d1a5a35673b3c94b12fe547129f3f"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3251726837b272028365446561d339ef635f5730"
os = "windows"

    [[jlqml.download]]
    sha256 = "5f49e7cdd42c5d09134511f75a6cfb505b4e71fe4df9122ca82df41219147ee0"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "592cf41c88805974062aa3788d7bcae50033ed18"
os = "windows"

    [[jlqml.download]]
    sha256 = "6b808bfe7ae76a2ba4f55660baa19364ca3b33d50c54db7f420a8a036b295b97"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[jlqml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e627ba1f696306ebe5cfd619c69a1a09a2bdeb66"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "a4b2ac39496caa608c8e7a48b5f88806ae2da4e66c09efa6e3161937fda28888"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f355ad08f8657f2f26161f97191a243874b499a"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "c1974c6bfc09ec9ccba49e761044f4d72e659885caabf01bbf91908f4d1a04fe"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
git-tree-sha1 = "3c0466f1964a75e59382b84226f95f9e9c1122fb"
os = "macos"

    [[jlqml.download]]
    sha256 = "5407ca104e4ec20c526f51134260926b4acd164fcae7ed9f5fbe3d9c2481fa1c"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-apple-darwin.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "649a0d00881567de4c4e0f951d10d2049510ddbb"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "6eb66cdc949b74b1859d0dc1cb6e1ea6632281bca54920009158d617104082b4"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "319a22e7b878c7ae592c20dad9d2e60904080a11"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "06524a3c6529a0a8069574998dae8fcb4138186ef71872973cd120fa57cc3166"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
git-tree-sha1 = "81c6b210118a1d4f99968adf75d996d2b62577c8"
os = "freebsd"

    [[jlqml.download]]
    sha256 = "50a0c9f361c30f2ae3ed305ff114399ddec8e37d9d5f691ebf7ae9a36569707c"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d7f3fcd261989adb48efb528a973bce26e1d752"
os = "windows"

    [[jlqml.download]]
    sha256 = "101916bf0ca537946ad70f3a80abd846a9d753399573bee64a50033934398a32"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03644d1f98c6f89fa1e1e1ec4803f7f071898da6"
os = "windows"

    [[jlqml.download]]
    sha256 = "1b27e9488d357d7392cf75e09358d6f7dc44695603fb4898527c9a4924eeef2e"
    url = "https://github.com/barche/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
